# Generated by Django 5.0.2 on 2024-02-29 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='task',
            name='low',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='middle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
