# Generated by Django 5.0.2 on 2024-03-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0002_alter_task_subtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_users',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_users',
            field=models.JSONField(default=list),
        ),
    ]
