# Generated by Django 5.0.2 on 2024-03-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0003_remove_task_assigned_users_task_assigned_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
