# Generated by Django 5.0.2 on 2024-03-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0004_alter_task_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
