# Generated by Django 5.0.2 on 2024-04-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0008_alter_task_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('identifier', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
