# Generated by Django 5.0.2 on 2024-04-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0010_remove_task_assigned_users_task_assigned_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(to='task_board.task'),
        ),
    ]
