# Generated by Django 5.0.2 on 2024-04-03 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0013_alter_task_assigned_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tasks',
        ),
    ]
