# Generated by Django 5.0.2 on 2024-04-04 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0016_user_assigned_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assigned_tasks',
            field=models.ManyToManyField(null=True, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
