# Generated by Django 5.0.2 on 2024-04-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0017_alter_user_assigned_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_tasks',
        ),
    ]
